import './api/runtime-env.js';
import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import WebSocket from 'ws';

const app=express();
const __filename=fileURLToPath(import.meta.url);const __dirname=path.dirname(__filename);
const FRONTEND_ORIGIN=(process.env.FRONTEND_ORIGIN||'https://goonfx.com').replace(/\/$/,'');
const DERIV_CLIENT_ID=process.env.DERIV_CLIENT_ID||'';const DERIV_CLIENT_SECRET=process.env.DERIV_CLIENT_SECRET||'';const DERIV_REDIRECT_URI=process.env.DERIV_REDIRECT_URI||'https://goonfx.com/callback.html';const DERIV_APP_ID=process.env.DERIV_APP_ID||DERIV_CLIENT_ID;const SESSION_SECRET=process.env.SESSION_SECRET||'';
const PUBLIC_WS='wss://api.derivws.com/trading/v1/options/ws/public';const DERIV_API='https://api.derivws.com';const FRONTEND_DIR=path.resolve(__dirname,'../docs');
app.set('trust proxy',1);app.use(cors({origin:FRONTEND_ORIGIN,credentials:true,methods:['GET','POST','OPTIONS'],allowedHeaders:['Content-Type','Authorization']}));app.use(express.json({limit:'300kb'}));app.use(express.static(FRONTEND_DIR,{index:'index.html',fallthrough:true}));
app.get('/',(req,res)=>req.hostname==='api.goonfx.com'?res.json({ok:true,service:'GOON FX API',status:'online',trading:tradeReady(),oauth:oauthReady()}):res.sendFile(path.join(FRONTEND_DIR,'index.html')));app.get('/health',(_,res)=>res.json({ok:true,service:'goonfx-api',trading:tradeReady(),oauth:oauthReady(),missing:missingConfig()}));
const missingConfig=()=>['DERIV_CLIENT_ID','DERIV_APP_ID','DERIV_REDIRECT_URI','SESSION_SECRET'].filter(k=>!({DERIV_CLIENT_ID,DERIV_APP_ID,DERIV_REDIRECT_URI,SESSION_SECRET}[k]));const oauthReady=()=>missingConfig().length===0;const tradeReady=()=>oauthReady();
const key=()=>crypto.createHash('sha256').update(SESSION_SECRET).digest();function seal(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',key(),iv),e=Buffer.concat([c.update(v,'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),e]).toString('base64url')}function open(v){const b=Buffer.from(v,'base64url'),d=crypto.createDecipheriv('aes-256-gcm',key(),b.subarray(0,12));d.setAuthTag(b.subarray(12,28));return Buffer.concat([d.update(b.subarray(28)),d.final()]).toString('utf8')}function cookieToken(req){const raw=(req.headers.cookie||'').match(/(?:^|; )gx_token=([^;]+)/)?.[1];if(!raw||!SESSION_SECRET)return null;try{const p=JSON.parse(open(raw));return p.exp>Date.now()?p.token:null}catch{return null}}function setSession(res,t,e){const maxAge=Math.min(Math.max(Number(e||3600),300),86400);res.setHeader('Set-Cookie',`gx_token=${seal(JSON.stringify({token:t,exp:Date.now()+maxAge*1000}))}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`);return maxAge}function clearSession(res){res.setHeader('Set-Cookie','gx_token=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0')}function fail(res,e,code=400){res.status(e.status||code).json({error:e.message||'Request failed',details:e.data||null})}
async function derivToken({code,code_verifier}){const p=new URLSearchParams({grant_type:'authorization_code',client_id:DERIV_CLIENT_ID,code,code_verifier,redirect_uri:DERIV_REDIRECT_URI});if(DERIV_CLIENT_SECRET)p.set('client_secret',DERIV_CLIENT_SECRET);const r=await fetch('https://auth.deriv.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:p});const text=await r.text();let d;try{d=JSON.parse(text)}catch{d={error:text}}if(!r.ok){const e=new Error(d.error_description||d.error||`Deriv token exchange HTTP ${r.status}`);e.status=r.status;e.data=d;throw e}if(!d.access_token)throw new Error('Deriv did not return an access token');return d}
app.get('/api/oauth/config',(_,res)=>res.json({ok:true,client_id:DERIV_CLIENT_ID,redirect_uri:DERIV_REDIRECT_URI,scope:'trade',backend_ready:oauthReady(),missing:missingConfig()}));app.post('/api/oauth/exchange',async(req,res)=>{try{if(!oauthReady())throw new Error(`OAuth backend is incomplete: ${missingConfig().join(', ')}`);const {code,code_verifier,redirect_uri,client_id}=req.body||{};if(!code||!code_verifier)throw new Error('Authorization code or PKCE verifier is missing');if(redirect_uri!==DERIV_REDIRECT_URI||client_id!==DERIV_CLIENT_ID)throw new Error('OAuth client configuration mismatch');const t=await derivToken({code,code_verifier});res.json({ok:true,expires_in:setSession(res,t.access_token,t.expires_in)})}catch(e){fail(res,e)}});app.post('/api/logout',(_,r)=>{clearSession(r);r.json({ok:true})});
async function rest(p,token,o={}){const r=await fetch(`${DERIV_API}${p}`,{...o,headers:{Authorization:`Bearer ${token}`,'Deriv-App-ID':DERIV_APP_ID,...(o.headers||{})}});const text=await r.text();let d;try{d=JSON.parse(text)}catch{d={raw:text}}if(!r.ok){const e=new Error(d?.errors?.[0]?.message||d?.message||`Deriv API HTTP ${r.status}`);e.status=r.status;e.data=d;throw e}return d}
function ws(url,payload){return new Promise((resolve,reject)=>{const w=new WebSocket(url);const timer=setTimeout(()=>{try{w.close()}catch{}reject(new Error('Deriv WebSocket timeout'))},15000);let done=false;const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);try{w.close()}catch{}fn(v)};w.on('open',()=>w.send(JSON.stringify(payload)));w.on('message',raw=>{let d;try{d=JSON.parse(raw)}catch{return}if(d.error){const e=new Error(d.error.message||'Deriv WebSocket error');e.data=d;return finish(reject,e)}finish(resolve,d)});w.on('error',e=>finish(reject,e))})}
async function accounts(token){const d=await rest('/trading/v1/options/accounts',token);const a=d?.data;return Array.isArray(a)?a:(a?[a]:[])}async function resolveAccount(token,id){const a=await accounts(token);if(!a.length)throw new Error('No Deriv Options account is available');if(id){const f=a.find(x=>String(x.account_id)===String(id));if(!f)throw new Error('Selected Deriv account is unavailable');return f}return a[0]}
async function otpUrl(token,id){const account=await resolveAccount(token,id);const o=await rest(`/trading/v1/options/accounts/${encodeURIComponent(account.account_id)}/otp`,token,{method:'POST'});if(!o?.data?.url)throw new Error('Deriv did not return an authenticated WebSocket URL');return {account,url:o.data.url}}
function num(v,f=0){const n=Number(v);return Number.isFinite(n)?n:f}
const TYPES=new Set(['DIGITMATCH','DIGITDIFF','DIGITEVEN','DIGITODD','DIGITOVER','DIGITUNDER','HIGHER','LOWER','ONETOUCH','NOTOUCH','MULTUP','MULTDOWN','UPORDOWN','ACCU','TURBOSLONG','TURBOSSHORT','VANILLALONGCALL','VANILLALONGPUT','CALL','PUT']);
function params(body,account){const type=String(body.contract_type||body.contractType||'').toUpperCase();if(!TYPES.has(type))throw new Error(`Unsupported contract type: ${type||'missing'}`);const amount=num(body.amount??body.stake,NaN);if(!Number.isFinite(amount)||amount<=0)throw new Error('A valid stake is required');const symbol=String(body.underlying_symbol||body.symbol||'').trim();if(!symbol)throw new Error('A Deriv market symbol is required');const p={amount,basis:body.basis==='payout'?'payout':'stake',contract_type:type,currency:String(account.currency||body.currency||''),underlying_symbol:symbol};if(type==='ACCU'){const g=num(body.growth_rate??body.growthRate,NaN);if(!Number.isFinite(g)||g<=0)throw new Error('Accumulator growth rate is required');p.growth_rate=g}else if(['DIGITMATCH','DIGITDIFF','DIGITOVER','DIGITUNDER'].includes(type)){const b=String(body.barrier??body.digit??'').trim();if(!/^\d$/.test(b))throw new Error('Digit contracts require a prediction digit from 0 to 9');p.barrier=b}if(body.duration!==undefined)p.duration=Math.max(1,Math.floor(num(body.duration,1)));if(body.duration_unit)p.duration_unit=String(body.duration_unit);if(body.multiplier!==undefined)p.multiplier=num(body.multiplier);if(body.barrier2!==undefined&&body.barrier2!=='')p.barrier2=String(body.barrier2);return p}
function sameSocketTrade(url,proposalPayload){return new Promise((resolve,reject)=>{const socket=new WebSocket(url);let stage='proposal',closed=false,req=100;const timer=setTimeout(()=>{if(closed)return;closed=true;try{socket.close()}catch{}reject(new Error('Deriv trade connection timed out'))},20000);const finish=(fn,v)=>{if(closed)return;closed=true;clearTimeout(timer);try{socket.close()}catch{}fn(v)};socket.on('open',()=>socket.send(JSON.stringify({...proposalPayload,req_id:req++})));socket.on('message',raw=>{let d;try{d=JSON.parse(raw)}catch{return}if(d.error){const e=new Error(d.error.message||'Deriv trade error');e.data=d;return finish(reject,e)}if(stage==='proposal'){if(d.msg_type!=='proposal')return;const id=d.proposal?.id;const price=Number(d.proposal?.ask_price);if(!id||!Number.isFinite(price)||price<=0)return finish(reject,new Error('Deriv returned an invalid trade price'));stage='buy';socket.send(JSON.stringify({buy:String(id),price,req_id:req++}));return}if(stage==='buy'&&d.msg_type==='buy'){if(!d.buy?.contract_id)return finish(reject,new Error('Deriv returned a buy response without a contract ID'));return finish(resolve,d)}});socket.on('error',e=>finish(reject,e));socket.on('close',()=>{if(!closed)finish(reject,new Error('Deriv trade connection closed before buy confirmation'))})})}
app.get('/api/account',async(req,res)=>{try{const t=cookieToken(req);if(!t)return res.status(401).json({error:'Not connected'});const a=await accounts(t);res.json({ok:true,accounts:a,selected:a[0]?.account_id||null})}catch(e){fail(res,e,502)}});
app.get('/api/markets',async(_,res)=>{try{const d=await ws(PUBLIC_WS,{active_symbols:'full',req_id:1});res.json({ok:true,markets:d.active_symbols||[]})}catch(e){fail(res,e,502)}});app.get('/api/markets/:symbol/contracts',async(req,res)=>{try{const d=await ws(PUBLIC_WS,{contracts_for:req.params.symbol,req_id:1});res.json({ok:true,symbol:req.params.symbol,contracts:d.contracts_for||{}})}catch(e){fail(res,e,502)}});app.get('/api/markets/:symbol/ticks',async(req,res)=>{try{const d=await ws(PUBLIC_WS,{ticks_history:req.params.symbol,count:Math.min(Math.max(Number(req.query.count||100),10),1000),end:'latest',style:'ticks',req_id:1});res.json({ok:true,symbol:req.params.symbol,history:d.history||null,times:d.times||null})}catch(e){fail(res,e,502)}});app.get('/api/markets/:symbol/tick',async(req,res)=>{try{const d=await ws(PUBLIC_WS,{ticks:req.params.symbol,req_id:1});res.json({ok:true,symbol:req.params.symbol,tick:d.tick||null})}catch(e){fail(res,e,502)}});
app.post('/api/proposal',async(req,res)=>{try{const t=cookieToken(req);if(!t)return res.status(401).json({error:'Not connected to Deriv. Sign in first.'});const {account,url}=await otpUrl(t,req.body?.account_id);const d=await ws(url,{proposal:1,subscribe:0,req_id:1,...params(req.body||{},account)});res.json({ok:true,proposal:d.proposal,account})}catch(e){fail(res,e)}});
app.post('/api/trade',async(req,res)=>{try{const t=cookieToken(req);if(!t)return res.status(401).json({error:'Not connected to Deriv. Sign in first.'});const {account,url}=await otpUrl(t,req.body?.account_id);const result=await sameSocketTrade(url,params(req.body||{},account));res.json({ok:true,executed:true,buy:result.buy,account})}catch(e){fail(res,e)}});
app.post('/api/buy',async(req,res)=>{try{const t=cookieToken(req);if(!t)return res.status(401).json({error:'Not connected to Deriv. Sign in first.'});const b=req.body||{};if(b.proposal_id){const price=num(b.price,NaN);if(!Number.isFinite(price)||price<=0)throw new Error('A valid purchase price is required');const {account,url}=await otpUrl(t,b.account_id);const result=await ws(url,{buy:String(b.proposal_id),price,req_id:1});return res.json({ok:true,executed:Boolean(result?.buy?.contract_id),...result,account})}const {account,url}=await otpUrl(t,b.account_id);const result=await sameSocketTrade(url,params(b,account));res.json({ok:true,executed:true,buy:result.buy,account})}catch(e){fail(res,e)}});
app.post('/api/sell',async(req,res)=>{try{const t=cookieToken(req);if(!t)return res.status(401).json({error:'Not connected to Deriv. Sign in first.'});if(!req.body?.contract_id)throw new Error('Contract ID is required');const {account,url}=await otpUrl(t,req.body.account_id);const result=await ws(url,{sell:String(req.body.contract_id),price:num(req.body.price,0),req_id:1});res.json({ok:true,...result,account})}catch(e){fail(res,e)}});
app.post('/api/contract',async(req,res)=>{try{const t=cookieToken(req);if(!t)return res.status(401).json({error:'Not connected to Deriv. Sign in first.'});if(!req.body?.contract_id)throw new Error('Contract ID is required');const {account,url}=await otpUrl(t,req.body.account_id);const result=await ws(url,{proposal_open_contract:1,contract_id:Number(req.body.contract_id),subscribe:req.body.subscribe===false?0:1,req_id:1});res.json({ok:true,...result,account})}catch(e){fail(res,e)}});
app.post('/api/portfolio',async(req,res)=>{try{const t=cookieToken(req);if(!t)return res.status(401).json({error:'Not connected to Deriv. Sign in first.'});const {account,url}=await otpUrl(t,req.body?.account_id);const result=await ws(url,{portfolio:1,subscribe:1,req_id:1});res.json({ok:true,...result,account})}catch(e){fail(res,e)}});
app.get('*',(req,res,next)=>{if(req.path.startsWith('/api/'))return next();const f=path.join(FRONTEND_DIR,req.path);if(f.startsWith(FRONTEND_DIR)&&path.extname(f))return res.sendFile(f,err=>err?next():undefined);res.sendFile(path.join(FRONTEND_DIR,'index.html'))});
export default app;
