import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import WebSocket from 'ws';

const app = express();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const FRONTEND_DIR = path.resolve(__dirname, '../docs');
const ORIGIN = (process.env.FRONTEND_ORIGIN || 'https://goonfx.com').replace(/\/$/, '');
const APP_ID = process.env.DERIV_APP_ID || process.env.DERIV_CLIENT_ID || '34b2ctEChXoL5t579q8pB';
const CLIENT_ID = process.env.DERIV_CLIENT_ID || APP_ID;
const REDIRECT_URI = process.env.DERIV_REDIRECT_URI || 'https://goonfx.com/callback.html';
const SESSION_SECRET = process.env.SESSION_SECRET || '';
const DERIV_REST = 'https://api.derivws.com';
const PUBLIC_WS = 'wss://api.derivws.com/trading/v1/options/ws/public';

app.set('trust proxy', 1);
app.use(cors({ origin: ORIGIN, credentials: true, methods: ['GET','POST','OPTIONS'], allowedHeaders: ['Content-Type','Authorization'] }));
app.use(express.json({ limit: '300kb' }));
app.use(express.static(FRONTEND_DIR, { index: 'index.html' }));

function key(){ return crypto.createHash('sha256').update(SESSION_SECRET || 'goonfx-session').digest(); }
function seal(value){ const iv=crypto.randomBytes(12); const c=crypto.createCipheriv('aes-256-gcm',key(),iv); const e=Buffer.concat([c.update(value,'utf8'),c.final()]); return Buffer.concat([iv,c.getAuthTag(),e]).toString('base64url'); }
function unseal(value){ const b=Buffer.from(value,'base64url'); const d=crypto.createDecipheriv('aes-256-gcm',key(),b.subarray(0,12)); d.setAuthTag(b.subarray(12,28)); return Buffer.concat([d.update(b.subarray(28)),d.final()]).toString('utf8'); }
function cookie(req,name){ return (req.headers.cookie||'').match(new RegExp(`(?:^|; )${name}=([^;]+)`))?.[1] || null; }
function session(req){ const raw=cookie(req,'gx_token'); if(!raw)return null; try{const v=decodeURIComponent(raw);const d=SESSION_SECRET?JSON.parse(unseal(v)):JSON.parse(Buffer.from(v,'base64url').toString());return d.exp>Date.now()?d:null;}catch{return null;} }
function token(req){ return session(req)?.token || null; }
function selected(req){ const raw=cookie(req,'gx_account'); return raw ? decodeURIComponent(raw) : null; }
function setCookie(res,name,value,maxAge=3600){ res.append('Set-Cookie',`${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`); }
function clearCookies(res){ res.append('Set-Cookie','gx_token=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'); res.append('Set-Cookie','gx_account=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0'); }
function fail(res,e,status=400){res.status(e.status||status).json({error:e.message||'Request failed',details:e.data||null});}
function authHeaders(t){return {'Deriv-App-ID':APP_ID,'Authorization':`Bearer ${t}`,'Content-Type':'application/json'};}

async function derivRest(t,path,options={}){ const r=await fetch(DERIV_REST+path,{...options,headers:{...authHeaders(t),...(options.headers||{})}}); const text=await r.text(); let d={}; try{d=text?JSON.parse(text):{};}catch{d={error:text};} if(!r.ok){const msg=d?.errors?.[0]?.message||d?.error?.message||d?.error||`Deriv HTTP ${r.status}`;const e=new Error(msg);e.status=r.status;e.data=d;throw e;} return d; }
function normalizeAccount(a){ const id=a.account_id||a.id||a.loginid||a.login_id; const type=String(a.account_type||a.type||'').toLowerCase(); const isDemo=type==='demo'||type.includes('demo')||String(id||'').toUpperCase().startsWith('VR')||String(id||'').toUpperCase().startsWith('VRTC'); return {account_id:id,loginid:id,account_type:isDemo?'demo':'real',mode:isDemo?'DEMO':'REAL',balance:a.balance??a.available_balance??0,currency:a.currency||'USD',status:a.status||'active',raw:a}; }
async function accounts(t){ const d=await derivRest(t,'/trading/v1/options/accounts'); const list=Array.isArray(d?.data)?d.data:Array.isArray(d?.data?.accounts)?d.data.accounts:Array.isArray(d?.accounts)?d.accounts:[]; return list.map(normalizeAccount).filter(a=>a.account_id); }
async function currentAccount(req,t){ const list=await accounts(t); if(!list.length)throw new Error('No Deriv Options trading account was returned for this login.'); const wanted=selected(req); return list.find(a=>a.account_id===wanted)||list.find(a=>a.account_type==='demo')||list[0]; }
async function otpUrl(t,accountId){ const d=await derivRest(t,`/trading/v1/options/accounts/${encodeURIComponent(accountId)}/otp`,{method:'POST'}); const url=d?.data?.url||d?.url; if(!url)throw new Error('Deriv did not return an authenticated WebSocket URL.'); return url; }

function wsRequest(url,requests,timeout=20000){return new Promise((resolve,reject)=>{const ws=new WebSocket(url);let done=false,timer;const out=[];const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);try{ws.close()}catch{}fn(v)};timer=setTimeout(()=>finish(reject,new Error('Deriv WebSocket timed out')),timeout);let i=0;ws.on('open',()=>ws.send(JSON.stringify({...requests[i++],req_id:i})));ws.on('message',raw=>{let d;try{d=JSON.parse(raw)}catch{return}if(d.error)return finish(reject,Object.assign(new Error(d.error.message||'Deriv WebSocket error'),{data:d}));out.push(d);if(i<requests.length)ws.send(JSON.stringify({...requests[i++],req_id:i}));else finish(resolve,out)});ws.on('error',e=>finish(reject,e));ws.on('close',()=>{if(!done)finish(reject,new Error('Deriv WebSocket closed'))})})}
async function tradeFlow(t,accountId,payload,execute){const url=await otpUrl(t,accountId);if(!execute){const r=await wsRequest(url,[payload]);return r.find(x=>x.msg_type==='proposal')||r[r.length-1];}const ws=new WebSocket(url);return await new Promise((resolve,reject)=>{let phase='proposal',done=false,timer=setTimeout(()=>finish(reject,new Error('Trade timed out')),25000),proposal;const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);try{ws.close()}catch{}fn(v)};ws.on('open',()=>ws.send(JSON.stringify({...payload,req_id:1})));ws.on('message',raw=>{let d;try{d=JSON.parse(raw)}catch{return}if(d.error)return finish(reject,Object.assign(new Error(d.error.message||'Deriv trading error'),{data:d}));if(phase==='proposal'&&d.msg_type==='proposal'){proposal=d.proposal;const id=proposal?.id,price=Number(proposal?.ask_price);if(!id||!Number.isFinite(price))return finish(reject,new Error('Invalid Deriv proposal returned'));phase='buy';ws.send(JSON.stringify({buy:String(id),price,req_id:2}));return}if(phase==='buy'&&d.msg_type==='buy'){if(!d.buy?.contract_id)return finish(reject,new Error('Deriv did not confirm the contract'));finish(resolve,{proposal,buy:d.buy})}});ws.on('error',e=>finish(reject,e));ws.on('close',()=>{if(!done)finish(reject,new Error('Deriv trade WebSocket closed'))})})}

const TYPES=new Set(['DIGITEVEN','DIGITODD','DIGITOVER','DIGITUNDER','DIGITMATCH','DIGITDIFF']);
function params(body,account){const type=String(body.contract_type||'').toUpperCase();if(!TYPES.has(type))throw new Error('Only Even, Odd, Over and Under are enabled here.');const amount=Number(body.amount??body.stake);if(!Number.isFinite(amount)||amount<=0)throw new Error('Enter a valid stake.');const symbol=String(body.underlying_symbol||body.symbol||'').trim();if(!symbol)throw new Error('Select a Deriv market.');const unit=String(body.duration_unit||'t');if(!['t','s','m','h','d'].includes(unit))throw new Error('Invalid duration unit.');const p={proposal:1,amount,basis:'stake',contract_type:type,currency:account.currency,underlying_symbol:symbol,duration:Math.max(1,Math.floor(Number(body.duration||1))),duration_unit:unit};if(['DIGITOVER','DIGITUNDER','DIGITMATCH','DIGITDIFF'].includes(type)){const b=String(body.barrier??body.digit??'');if(!/^\d$/.test(b))throw new Error('Digit contracts require a digit from 0 to 9.');p.barrier=b;}return p;}

app.get('/health',(_,res)=>res.json({ok:true,service:'goonfx-api',oauth:Boolean(APP_ID&&CLIENT_ID&&REDIRECT_URI),trading:true,api:'deriv-options-v1'}));
app.get('/api/oauth/config',(_,res)=>res.json({ok:true,client_id:CLIENT_ID,app_id:APP_ID,redirect_uri:REDIRECT_URI,scope:'trade',backend_ready:Boolean(APP_ID&&CLIENT_ID&&REDIRECT_URI)}));
app.post('/api/oauth/exchange',async(req,res)=>{try{const {code,code_verifier,redirect_uri,client_id}=req.body||{};if(!code||!code_verifier)throw new Error('Authorization code or PKCE verifier is missing.');if(redirect_uri!==REDIRECT_URI||client_id!==CLIENT_ID)throw new Error('OAuth configuration mismatch.');const body=new URLSearchParams({grant_type:'authorization_code',client_id:CLIENT_ID,code,code_verifier,redirect_uri});const r=await fetch('https://auth.deriv.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={error:text}}if(!r.ok||!d.access_token){const e=new Error(d.error_description||d.error||`OAuth exchange failed (${r.status})`);e.status=r.status;e.data=d;throw e;}const maxAge=Math.min(Math.max(Number(d.expires_in)||3600,300),86400);const payload=JSON.stringify({token:d.access_token,exp:Date.now()+maxAge*1000});setCookie(res,'gx_token',SESSION_SECRET?seal(payload):Buffer.from(payload).toString('base64url'),maxAge);res.json({ok:true,expires_in:maxAge});}catch(e){fail(res,e)}});
app.post('/api/logout',(_,res)=>{clearCookies(res);res.json({ok:true})});

app.get('/api/accounts',async(req,res)=>{try{const t=token(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const list=await accounts(t);if(!list.length)return res.status(404).json({error:'No Options trading accounts found.'});const wanted=selected(req);const current=list.find(a=>a.account_id===wanted)||list.find(a=>a.account_type==='demo')||list[0];res.json({ok:true,accounts:list.map(({raw,...a})=>a),current});}catch(e){fail(res,e,502)}});
app.post('/api/select-account',async(req,res)=>{try{const t=token(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const id=String(req.body?.account_id||'');if(!id)throw new Error('Account ID is required.');const list=await accounts(t);const a=list.find(x=>x.account_id===id);if(!a)throw new Error('That account is not available for the current Deriv login.');setCookie(res,'gx_account',id,86400);res.json({ok:true,current:a});}catch(e){fail(res,e)}});
app.get('/api/account',async(req,res)=>{try{const t=token(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await currentAccount(req,t);res.json({ok:true,account:a,balance:a.balance,currency:a.currency,loginid:a.loginid,mode:a.mode,account_type:a.account_type});}catch(e){fail(res,e,502)}});
app.get('/api/balance',async(req,res)=>{try{const t=token(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await currentAccount(req,t);res.json({ok:true,balance:a.balance,currency:a.currency,loginid:a.loginid,mode:a.mode});}catch(e){fail(res,e,502)}});

async function publicWs(request,timeout=12000){const ws=new WebSocket(PUBLIC_WS);return await new Promise((resolve,reject)=>{let done=false,timer=setTimeout(()=>finish(reject,new Error('Market feed timed out')),timeout);const finish=(fn,v)=>{if(done)return;done=true;clearTimeout(timer);try{ws.close()}catch{}fn(v)};ws.on('open',()=>ws.send(JSON.stringify({...request,req_id:1})));ws.on('message',raw=>{try{const d=JSON.parse(raw);if(d.error)return finish(reject,new Error(d.error.message));finish(resolve,d)}catch(e){finish(reject,e)}});ws.on('error',e=>finish(reject,e));ws.on('close',()=>{if(!done)finish(reject,new Error('Public market connection closed'))})})}
app.get('/api/markets',async(_,res)=>{try{const d=await publicWs({active_symbols:'brief'});res.json({ok:true,markets:d.active_symbols||d.data||[]})}catch(e){fail(res,e,502)}});
app.get('/api/markets/:symbol/ticks',async(req,res)=>{try{const count=Math.min(Math.max(Number(req.query.count||150),10),1000);const d=await publicWs({ticks_history:req.params.symbol,count,end:'latest',style:'ticks'});res.json({ok:true,symbol:req.params.symbol,history:d.history||null,times:d.times||null})}catch(e){fail(res,e,502)}});

app.post('/api/proposal',async(req,res)=>{try{const t=token(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await currentAccount(req,t);const p=params(req.body||{},a);const d=await tradeFlow(t,a.account_id,p,false);res.json({ok:true,proposal:d.proposal||d,account:a});}catch(e){fail(res,e,502)}});
app.post('/api/proposal-real',async(req,res)=>{try{const t=token(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await currentAccount(req,t);const p=params(req.body||{},a);const d=await tradeFlow(t,a.account_id,p,false);res.json({ok:true,proposal:d.proposal||d,account:a});}catch(e){fail(res,e,502)}});
app.post('/api/trade',async(req,res)=>{try{const t=token(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await currentAccount(req,t);const d=await tradeFlow(t,a.account_id,params(req.body||{},a),true);res.json({ok:true,executed:true,account:a,contract_id:d.buy.contract_id,transaction_id:d.buy.transaction_id||null,buy:d.buy,proposal:d.proposal});}catch(e){fail(res,e,502)}});
app.post('/api/buy',async(req,res)=>{try{const t=token(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await currentAccount(req,t);const id=String(req.body?.proposal_id||'');const price=Number(req.body?.price);if(!id||!Number.isFinite(price)||price<=0)throw new Error('A valid proposal ID and price are required.');const url=await otpUrl(t,a.account_id);const result=await wsRequest(url,[{buy:id,price}]);const d=result.find(x=>x.msg_type==='buy')||result[result.length-1];res.json({ok:true,executed:Boolean(d?.buy?.contract_id),account:a,...d});}catch(e){fail(res,e,502)}});
app.post('/api/sell',async(req,res)=>{try{const t=token(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await currentAccount(req,t);const id=String(req.body?.contract_id||'');if(!id)throw new Error('Contract ID is required.');const url=await otpUrl(t,a.account_id);const result=await wsRequest(url,[{sell:id,price:Number(req.body?.price||0)}]);const d=result.find(x=>x.msg_type==='sell')||result[result.length-1];res.json({ok:true,account:a,...d});}catch(e){fail(res,e,502)}});

app.get('*',(req,res,next)=>{if(req.path.startsWith('/api/'))return next();res.sendFile(path.join(FRONTEND_DIR,req.path==='/'?'index.html':req.path.replace(/^\//,'')),err=>{if(err)res.sendFile(path.join(FRONTEND_DIR,'index.html'))})});
export default app;
