import express from 'express';
import cors from 'cors';
import WebSocket from 'ws';

const app = express();
const ORIGIN = process.env.FRONTEND_ORIGIN || 'https://goonfx.com';
const CLIENT_ID = process.env.DERIV_CLIENT_ID || '348AuAfk8ZpsbSW8Whqc3';
const API_APP_ID = process.env.DERIV_API_APP_ID || process.env.DERIV_APP_ID || '34b2ctEChXoL5t579q8pB';
const REDIRECT_URI = process.env.DERIV_REDIRECT_URI || 'https://goonfx.com/';
const REST = 'https://api.derivws.com';
const PUBLIC_WS = 'wss://api.derivws.com/trading/v1/options/ws/public';

const ALLOWED_ORIGINS = new Set([
  ORIGIN,
  'https://goonfx.com',
  'https://arnold956.github.io',
  'https://goonfx-nkyefadc4-arnoldrodgers14-9689s-projects.vercel.app',
  'https://goonfx-arnoldrodgers14-9689s-projects.vercel.app',
  'https://goonfx-git-main-arnoldrodgers14-9689s-projects.vercel.app'
]);
app.use(cors({ origin(origin, cb) { if (!origin || ALLOWED_ORIGINS.has(origin)) return cb(null, true); return cb(new Error('Origin not allowed')); }, credentials: true, methods: ['GET','POST','OPTIONS'], allowedHeaders: ['Content-Type','Authorization'] }));
app.use(express.json({ limit: '300kb' }));
app.use((req, res, next) => { if (req.url === '/api' || req.url.startsWith('/api/')) req.url = req.url.slice(4) || '/'; next(); });
function getCookie(req,name){const m=(req.headers.cookie||'').match(new RegExp(`(?:^|; )${name}=([^;]+)`));return m?decodeURIComponent(m[1]):null}
function setCookie(res,name,value,maxAge=86400){res.append('Set-Cookie',`${name}=${encodeURIComponent(value)}; Domain=.goonfx.com; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`)}
function bearer(req){return getCookie(req,'gx_token')}
function fail(res,err,status=400){res.status(err.status||status).json({error:err.message||'Request failed',details:err.data||null})}
function derivHeaders(token){if(!token)throw new Error('Deriv access token is missing.');const h={Authorization:`Bearer ${token}`,'Content-Type':'application/json'};if(API_APP_ID)h['Deriv-App-ID']=API_APP_ID;return h}
async function deriv(token,path,options={}){const r=await fetch(REST+path,{...options,headers:{...derivHeaders(token),...(options.headers||{})}});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!r.ok){const e=new Error(data?.errors?.[0]?.message||data?.error_description||data?.error||`Deriv HTTP ${r.status}`);e.status=r.status;e.data=data;throw e}return data}
function wsOnce(url,payload,timeout=15000){return new Promise((resolve,reject)=>{const ws=new WebSocket(url);let done=false;const finish=(fn,value)=>{if(done)return;done=true;clearTimeout(timer);try{ws.close()}catch{}fn(value)};const timer=setTimeout(()=>finish(reject,new Error('Deriv trading connection timed out')),timeout);ws.on('open',()=>ws.send(JSON.stringify({...payload,req_id:1})));ws.on('message',raw=>{try{const d=JSON.parse(raw);if(d.error)return finish(reject,new Error(d.error.message||'Deriv trading error'));finish(resolve,d)}catch(e){finish(reject,e)}});ws.on('error',e=>finish(reject,e));ws.on('close',()=>{if(!done)finish(reject,new Error('Deriv WebSocket closed'))})})}
function publicWs(payload,timeout=15000){return wsOnce(PUBLIC_WS,payload,timeout)}
async function otp(token,accountId){const d=await deriv(token,`/trading/v1/options/accounts/${encodeURIComponent(accountId)}/otp`,{method:'POST'});const url=d?.data?.url||d?.url;if(!url)throw new Error('Deriv did not return an authenticated trading WebSocket URL.');return url}
async function balanceFor(token,accountId){const url=await otp(token,accountId);const d=await wsOnce(url,{balance:1});const b=d?.balance||d?.data||{};return {balance:Number(b.balance??b.amount??0),currency:b.currency||'USD'}}
async function accounts(token){const d=await deriv(token,'/trading/v1/options/accounts');const list=Array.isArray(d?.data)?d.data:Array.isArray(d?.data?.accounts)?d.data.accounts:Array.isArray(d?.accounts)?d.accounts:[];const normalized=list.filter(x=>x.account_id||x.id||x.loginid).map(x=>{const id=x.account_id||x.id||x.loginid;const typ=String(x.account_type||x.type||'').toLowerCase();const demo=typ.includes('demo')||/^VR|^VRTC/i.test(id);return {...x,account_id:id,account_type:demo?'demo':'real',mode:demo?'DEMO':'REAL',currency:x.currency||'USD'}});return Promise.all(normalized.map(async a=>{try{const b=await balanceFor(token,a.account_id);return {...a,balance:b.balance,currency:b.currency||a.currency}}catch{return {...a,balance:Number(a.balance||0)}}}))}
async function selectedAccount(token,req){const list=await accounts(token);if(!list.length)throw new Error('No Deriv trading account is available.');const selected=getCookie(req,'gx_account');return list.find(a=>a.account_id===selected)||list.find(a=>a.account_type==='demo')||list[0]}
function tradeParams(body,account){const type=String(body.contract_type||'').toUpperCase();const allowed=new Set(['CALL','PUT','DIGITEVEN','DIGITODD','DIGITOVER','DIGITUNDER','DIGITMATCH','DIGITDIFF','HIGHER','LOWER','UPORDOWN','ONETOUCH','NOTOUCH','MULTUP','MULTDOWN','TICKHIGH','TICKLOW']);if(!allowed.has(type))throw new Error('Unsupported contract type.');const amount=Number(body.amount??body.stake);if(!Number.isFinite(amount)||amount<=0)throw new Error('Enter a valid stake.');const symbol=String(body.underlying_symbol||body.symbol||'').trim();if(!symbol)throw new Error('Select a market.');const duration=Math.max(1,Math.floor(Number(body.duration||1))),unit=String(body.duration_unit||'t');if(!['t','s','m','h','d'].includes(unit))throw new Error('Invalid duration unit.');const p={amount,basis:'stake',contract_type:type,currency:account.currency||'USD',underlying_symbol:symbol,duration,duration_unit:unit};if(['DIGITOVER','DIGITUNDER','DIGITMATCH','DIGITDIFF'].includes(type)){const digit=String(body.barrier??body.digit??'');if(!/^\d$/.test(digit))throw new Error('Choose a digit 0-9.');p.barrier=digit}if(['HIGHER','LOWER','ONETOUCH','NOTOUCH'].includes(type)){const barrier=String(body.barrier??'');if(barrier)p.barrier=barrier}if(['MULTUP','MULTDOWN'].includes(type))p.multiplier=Number(body.multiplier||10);return p}
async function proposal(token,account,params){const url=await otp(token,account.account_id);const d=await wsOnce(url,{proposal:1,...params,subscribe:0});if(!d.proposal)throw new Error(d.error?.message||'Deriv did not return a proposal for this market and contract.');return d.proposal}
async function buy(token,account,proposalId,price){const url=await otp(token,account.account_id);const d=await wsOnce(url,{buy:String(proposalId),price:Number(price)});if(!d.buy)throw new Error(d.error?.message||'Deriv did not confirm the purchase.');return d.buy}
async function accountRequest(token,accountId,payload){const url=await otp(token,accountId);return wsOnce(url,payload)}

app.get('/health',(_,res)=>res.json({ok:true,service:'goonfx-api',oauth:true,trading:true,configured:Boolean(CLIENT_ID),legacy_app_id_configured:Boolean(API_APP_ID),redirect_uri:REDIRECT_URI}));
app.get('/oauth/config',(_,res)=>res.json({ok:true,client_id:CLIENT_ID,api_app_id_configured:Boolean(API_APP_ID),redirect_uri:REDIRECT_URI,scope:'trade'}));
app.post('/oauth/exchange',async(req,res)=>{try{const {code,code_verifier,redirect_uri,client_id}=req.body||{};if(!code||!code_verifier)throw new Error('Authorization code or PKCE verifier is missing.');if(redirect_uri!==REDIRECT_URI||client_id!==CLIENT_ID)throw new Error('OAuth configuration mismatch.');const body=new URLSearchParams({grant_type:'authorization_code',client_id:CLIENT_ID,code,code_verifier,redirect_uri:REDIRECT_URI});const r=await fetch('https://auth.deriv.com/oauth2/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const text=await r.text();let d={};try{d=JSON.parse(text)}catch{}if(!r.ok||!d.access_token)throw new Error(d.error_description||d.error||`OAuth exchange failed (${r.status})`);const max=Math.min(Math.max(Number(d.expires_in)||3600,300),86400);setCookie(res,'gx_token',d.access_token,max);res.json({ok:true,expires_in:max})}catch(e){fail(res,e)}});
app.post('/logout',(_,res)=>{setCookie(res,'gx_token','',0);setCookie(res,'gx_account','',0);res.json({ok:true})});
app.get('/accounts',async(req,res)=>{try{const t=bearer(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const list=await accounts(t);const id=getCookie(req,'gx_account');const current=list.find(a=>a.account_id===id)||list.find(a=>a.account_type==='demo')||list[0];if(current&&!id)setCookie(res,'gx_account',current.account_id);res.json({ok:true,accounts:list.map(a=>({account_id:a.account_id,account_type:a.account_type,mode:a.mode,balance:a.balance,currency:a.currency,status:a.status||'active'})),current})}catch(e){fail(res,e,502)}});
app.post('/select-account',async(req,res)=>{try{const t=bearer(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const id=String(req.body?.account_id||'');const a=(await accounts(t)).find(x=>x.account_id===id);if(!a)throw new Error('Selected account is not available.');setCookie(res,'gx_account',id);res.json({ok:true,current:a})}catch(e){fail(res,e)}});
app.get('/account',async(req,res)=>{try{const t=bearer(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await selectedAccount(t,req);res.json({ok:true,account:a,balance:a.balance,currency:a.currency,account_type:a.account_type,account_id:a.account_id})}catch(e){fail(res,e,502)}});
app.get('/balance',async(req,res)=>{try{const t=bearer(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await selectedAccount(t,req);res.json({ok:true,balance:a.balance,currency:a.currency,account_type:a.account_type,account_id:a.account_id})}catch(e){fail(res,e,502)}});
app.get('/markets',async(_,res)=>{try{const d=await publicWs({active_symbols:'brief'});res.json({ok:true,markets:(d.active_symbols||[]).map(x=>({symbol:x.underlying_symbol,underlying_symbol:x.underlying_symbol,display:x.underlying_symbol_name||x.display_name||x.underlying_symbol,market:x.market,submarket:x.submarket,exchange_is_open:x.exchange_is_open,is_trading_suspended:x.is_trading_suspended}))})}catch(e){fail(res,e,502)}});
app.get('/markets/:symbol/ticks',async(req,res)=>{try{const count=Math.min(Math.max(Number(req.query.count||150),10),1000);const d=await publicWs({ticks_history:req.params.symbol,count,end:'latest',style:'ticks'});res.json({ok:true,symbol:req.params.symbol,history:d.history||null,times:d.history?.times||d.times||null,prices:d.history?.prices||null})}catch(e){fail(res,e,502)}});
app.get('/markets/:symbol/contracts',async(req,res)=>{try{const d=await publicWs({contracts_for:req.params.symbol});res.json({ok:true,symbol:req.params.symbol,contracts:d.contracts_for?.available||[]})}catch(e){fail(res,e,502)}});
app.post('/proposal',async(req,res)=>{try{const t=bearer(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await selectedAccount(t,req);const p=await proposal(t,a,tradeParams(req.body||{},a));res.json({ok:true,account:a,proposal:p})}catch(e){fail(res,e,502)}});
app.post('/buy',async(req,res)=>{try{const t=bearer(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await selectedAccount(t,req);const id=String(req.body?.proposal_id||'');const price=Number(req.body?.price);if(!id||!Number.isFinite(price)||price<=0)throw new Error('Valid proposal ID and price are required.');const b=await buy(t,a,id,price);res.json({ok:true,executed:Boolean(b.contract_id),account:a,buy:b,contract_id:b.contract_id})}catch(e){fail(res,e,502)}});
app.get('/portfolio',async(req,res)=>{try{const t=bearer(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await selectedAccount(t,req);const d=await accountRequest(t,a.account_id,{portfolio:1});res.json({ok:true,account:a,contracts:d?.portfolio?.contracts||[]})}catch(e){fail(res,e,502)}});
app.get('/contracts/:id',async(req,res)=>{try{const t=bearer(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await selectedAccount(t,req);const d=await accountRequest(t,a.account_id,{proposal_open_contract:1,contract_id:Number(req.params.id)});res.json({ok:true,contract:d?.proposal_open_contract||null})}catch(e){fail(res,e,502)}});
app.post('/sell',async(req,res)=>{try{const t=bearer(req);if(!t)return res.status(401).json({error:'Not connected to Deriv.'});const a=await selectedAccount(t,req);const id=String(req.body?.contract_id||'');if(!id)throw new Error('Contract ID is required.');const url=await otp(t,a.account_id);const d=await wsOnce(url,{sell:id,price:Number(req.body?.price??0)});if(!d.sell)throw new Error(d.error?.message||'Deriv did not confirm the sale.');res.json({ok:true,account:a,sell:d.sell,contract_id:id})}catch(e){fail(res,e,502)}});

export default app;
